project_id = "gnrinwqmqhfasfojysep"

[functions.ggcheckout-webhook]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.integration-ai-assistant]
verify_jwt = false

[functions.generate-landing-theme]
verify_jwt = false