project_id = "gnrinwqmqhfasfojysep"

[functions.ggcheckout-webhook]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.integration-ai-assistant]
verify_jwt = false

[functions.generate-landing-theme]
verify_jwt = false

[functions.admin-members]
verify_jwt = false

[functions.admin-update-subscription]
verify_jwt = false

[functions.accept-team-invite]
verify_jwt = false

[functions.public-booking]

[functions.create-fake-user]
verify_jwt = false

[functions.financial-ai-assistant]
verify_jwt = false
